import AppLayout from "@/components/layouts/AppLayout";
import "@/styles/globals.css";
import "@/styles/sassStyle.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
